/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpenBoxRouteImport } from './routes/open-box'
import { Route as OpenRouteImport } from './routes/open'
import { Route as MarketRouteImport } from './routes/market'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'

const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenBoxRoute = OpenBoxRouteImport.update({
  id: '/open-box',
  path: '/open-box',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/market': typeof MarketRoute
  '/open': typeof OpenRoute
  '/open-box': typeof OpenBoxRoute
  '/profile': typeof ProfileRoute
  '/tournaments': typeof TournamentsRoute
  '/treasury': typeof TreasuryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/market': typeof MarketRoute
  '/open': typeof OpenRoute
  '/open-box': typeof OpenBoxRoute
  '/profile': typeof ProfileRoute
  '/tournaments': typeof TournamentsRoute
  '/treasury': typeof TreasuryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/market': typeof MarketRoute
  '/open': typeof OpenRoute
  '/open-box': typeof OpenBoxRoute
  '/profile': typeof ProfileRoute
  '/tournaments': typeof TournamentsRoute
  '/treasury': typeof TreasuryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/collection'
    | '/market'
    | '/open'
    | '/open-box'
    | '/profile'
    | '/tournaments'
    | '/treasury'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/collection'
    | '/market'
    | '/open'
    | '/open-box'
    | '/profile'
    | '/tournaments'
    | '/treasury'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/collection'
    | '/market'
    | '/open'
    | '/open-box'
    | '/profile'
    | '/tournaments'
    | '/treasury'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  CollectionRoute: typeof CollectionRoute
  MarketRoute: typeof MarketRoute
  OpenRoute: typeof OpenRoute
  OpenBoxRoute: typeof OpenBoxRoute
  ProfileRoute: typeof ProfileRoute
  TournamentsRoute: typeof TournamentsRoute
  TreasuryRoute: typeof TreasuryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-box': {
      id: '/open-box'
      path: '/open-box'
      fullPath: '/open-box'
      preLoaderRoute: typeof OpenBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  CollectionRoute: CollectionRoute,
  MarketRoute: MarketRoute,
  OpenRoute: OpenRoute,
  OpenBoxRoute: OpenBoxRoute,
  ProfileRoute: ProfileRoute,
  TournamentsRoute: TournamentsRoute,
  TreasuryRoute: TreasuryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
